# -*- coding: utf-8 -*-
"""ex2_mo430.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nlgxz8JU8WLDTUuPML9vkD7w9OSPBa-M

# Exercício 2

## Dados não pareados
"""

import numpy as np
import pandas as pd

path = 'ex2.csv'

"""### Teste T"""

import statsmodels.api as sm

diabetes = dados[dados.type == 'Yes'].bp.values
naoDiabetes = dados[dados.type == 'No'].bp.values

pvalue_t = sm.stats.ttest_ind(diabetes, naoDiabetes)[1]
pvalue_t

"""### Wilcoxon rank sum"""

from scipy.stats import ranksums

pvalue_wilcoxon = ranksums(diabetes, naoDiabetes).pvalue
pvalue_wilcoxon

mean_diabetes = np.mean(diabetes)
mean_naoDiabetes = np.mean(naoDiabetes)
mean_diabetes, mean_naoDiabetes

print("p-value T test:", pvalue_t)
print("p-value Wilkonson test:", pvalue_wilcoxon)

"""## Dados Pareados"""

path = 'ex2-paired.csv'

from scipy import stats

pvalue_tp = stats.ttest_rel(dados.August.values, dados.November.values).pvalue
pvalue_tp

from scipy.stats import wilcoxon

pvalue_wsr = wilcoxon(dados.August.values, dados.November.values).pvalue
pvalue_wsr

mean_aug = np.mean(dados.August.values)
mean_nov = np.mean(dados.November.values)

print('Media de Agosto:', mean_aug)
print('Media de Novembro:', mean_nov)

median_aug = np.median(dados.August.values) 
median_nov = np.median(dados.November.values)

print('Mediana de Agosto:', median_aug)
print('Mediana de Novembro:', median_nov)

print("p-value T test pareado:", pvalue_tp)
print("p-value Wilkonson Signed Rank test :", pvalue_wsr)